server:
  port: 9002
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8070
    loadbalancer:
      enabled: true
feign:
  sentinel:
    enabled: true